# Generated by Django 5.2.15 on 2026-07-30 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0131_project_overview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='type',
            field=models.CharField(choices=[('categories', 'Categories'), ('points', 'Points'), ('time', 'Time')], default='categories', max_length=255),
        ),
    ]
