# Generated by Django 5.2.15 on 2026-08-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0140_entityupdate_edited_at_entityupdatelabel'),
    ]

    operations = [
        migrations.AddField(
            model_name='workitemproperty',
            name='is_grouping_dimension',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='workitemproperty',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('is_grouping_dimension', True)), fields=('project',), name='work_item_property_one_grouping_dimension_per_project'),
        ),
    ]
