# Generated by Django 5.2.15 on 2026-08-04 10:05

from django.db import migrations, models


def mark_existing_parents_as_folders(apps, schema_editor):
    """Every page that already has children becomes a folder.

    This is what the product was drawing before the column existed -- the list rendered a
    folder icon for anything with sub-pages -- so the migration preserves what a user was
    already looking at rather than imposing a new shape on their tree.

    It also has to happen. From here on only a folder may take children, and without this
    pass every existing parent would be a page holding children it is no longer allowed to
    hold: the tree would still render, but the first edit to any of those rows would be
    rejected by a rule the data predates.

    Bodies are left alone. Three of the rows this touches on the authors' own instance have
    real prose in `description_html`, and while `is_folder` is true nothing reads it -- but
    deleting user text to satisfy a schema change is the worse of the two surprises, and
    keeping it means turning a folder back into a page restores what was written.
    """
    Page = apps.get_model("db", "Page")
    parent_ids = (
        Page.objects.filter(parent__isnull=False, deleted_at__isnull=True)
        .values_list("parent_id", flat=True)
        .distinct()
    )
    Page.objects.filter(id__in=list(parent_ids)).update(is_folder=True)


def unmark(apps, schema_editor):
    """Reverse: nothing is a folder once the column is going away."""
    Page = apps.get_model("db", "Page")
    Page.objects.filter(is_folder=True).update(is_folder=False)


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0142_workitemproperty_is_grouping_dimension_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="is_folder",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(mark_existing_parents_as_folders, unmark),
    ]
