# Generated by Django 5.2.15 on 2026-08-04 12:23

from django.db import migrations, models

#: The types this fork ships that describe work rather than a promise. Matched by name
#: **once**, here, against the vocabulary as it stands on the day of the migration -- which
#: is a different act from compiling those names into a query that runs forever.
#:
#: Everything else keeps the field default of true. That direction is deliberate: a type
#: this list does not recognise -- one a team renamed, or invented -- shows up as needing
#: acceptance, which is visible noise. Defaulting the other way would drop it out of the
#: report entirely, and a coverage gap that reports itself as covered is the failure worth
#: designing against.
NOT_REQUIREMENTS = ("Bug", "Task")


def classify_shipped_types(apps, schema_editor):
    IssueType = apps.get_model("db", "IssueType")
    IssueType.objects.filter(name__in=NOT_REQUIREMENTS).update(needs_acceptance=False)


def unclassify(apps, schema_editor):
    """Reverse: everything needs acceptance again, which is the field's default."""
    IssueType = apps.get_model("db", "IssueType")
    IssueType.objects.update(needs_acceptance=True)


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0143_page_is_folder"),
    ]

    operations = [
        migrations.AddField(
            model_name="issuetype",
            name="needs_acceptance",
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(classify_shipped_types, unclassify),
    ]
