# Generated by Django 5.2.15 on 2026-08-05 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0144_issuetype_needs_acceptance'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcaseversion',
            name='threshold_metric',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='testcaseversion',
            name='threshold_operator',
            field=models.CharField(blank=True, choices=[('lt', 'Less than'), ('lte', 'At most'), ('gt', 'Greater than'), ('gte', 'At least')], max_length=8),
        ),
        migrations.AddField(
            model_name='testcaseversion',
            name='threshold_unit',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='testcaseversion',
            name='threshold_value',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True),
        ),
    ]
