# Generated by Django 5.2.15 on 2026-08-06 04:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0146_team_calendar'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('colour', models.CharField(default='#6B7280', help_text='Hex, for the wallchart.', max_length=7)),
                ('consumes_capacity', models.BooleanField(default=True, help_text='False for absences that do not remove the person from work, e.g. working remotely.')),
                ('requires_approval', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.FloatField(default=65535)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_types', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Leave Type',
                'verbose_name_plural': 'Leave Types',
                'db_table': 'leave_types',
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='MemberLeave',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_day_part', models.CharField(choices=[('full', 'Full day'), ('morning', 'Morning'), ('afternoon', 'Afternoon')], default='full', max_length=16)),
                ('end_day_part', models.CharField(choices=[('full', 'Full day'), ('morning', 'Morning'), ('afternoon', 'Afternoon')], default='full', max_length=16)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=16)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_decisions', to=settings.AUTH_USER_MODEL)),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leaves', to='db.leavetype')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_leaves', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Member Leave',
                'verbose_name_plural': 'Member Leaves',
                'db_table': 'member_leaves',
                'ordering': ('-start_date',),
            },
        ),
        migrations.CreateModel(
            name='TeamEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_day_part', models.CharField(choices=[('full', 'Full day'), ('morning', 'Morning'), ('afternoon', 'Afternoon')], default='full', max_length=16)),
                ('end_day_part', models.CharField(choices=[('full', 'Full day'), ('morning', 'Morning'), ('afternoon', 'Afternoon')], default='full', max_length=16)),
                ('colour', models.CharField(default='#334155', max_length=7)),
                ('consumes_capacity', models.BooleanField(default=False, help_text='True for training or an offsite; false for a release date nobody attends.')),
                ('audience', models.CharField(choices=[('all_members', 'All members'), ('selected_members', 'Selected members')], default='all_members', help_text='Declared, not inferred from whether attendees happen to be listed.', max_length=32)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('project', models.ForeignKey(blank=True, help_text='Narrows what the event is about. Never narrows where an absence lives.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_events', to='db.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_events', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Team Event',
                'verbose_name_plural': 'Team Events',
                'db_table': 'team_events',
                'ordering': ('-start_date',),
            },
        ),
        migrations.CreateModel(
            name='TeamEventAttendee',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='db.teamevent')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_events', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_event_attendees', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Team Event Attendee',
                'verbose_name_plural': 'Team Event Attendees',
                'db_table': 'team_event_attendees',
            },
        ),
        migrations.AddConstraint(
            model_name='leavetype',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('workspace', 'name'), name='unique_active_leave_type_name'),
        ),
        migrations.AddIndex(
            model_name='memberleave',
            index=models.Index(fields=['workspace', 'start_date', 'end_date'], name='leave_range_idx'),
        ),
        migrations.AddIndex(
            model_name='memberleave',
            index=models.Index(fields=['member', 'start_date'], name='leave_member_idx'),
        ),
        migrations.AddIndex(
            model_name='teamevent',
            index=models.Index(fields=['workspace', 'start_date', 'end_date'], name='team_event_range_idx'),
        ),
        migrations.AddConstraint(
            model_name='teameventattendee',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('event', 'member'), name='unique_active_team_event_attendee'),
        ),
    ]
